# Generated by Django 2.2.16 on 2022-04-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_categories_comments_genres_review_titles'),
        ('reviews', '0002_categories_genres_titles'),
    ]

    operations = [
    ]
